In [1]:
import igl
import torch
import meshplot as mp
import numpy as np
from math import pi
from IPython.display import clear_output

In [49]:
v = np.array([[0, 0], [1, 0], [1, 1]])
v_d = np.array([[0, 0], [0, 1], [1, 1]])
f = np.array([[0, 1, 2]])

plt = mp.plot(v, f)
plt.update_object(oid = 0, vertices = v_d)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.5, 0.5,…

In [39]:
# # 파일에 저장
# x = torch.tensor([0, 1, 2, 3, 4])
# torch.save(x, 'tensor.pt')

x = torch.tensor([1, 2], dtype = float)
y = torch.tensor([2, 5], dtype = float)
z = x+y
print(z)
x[0] = 3
print(x)
print(z)
# print(x[1])
# print(y[1])
print(z)
# print(z.T)
# print(x@y.T)
# print(x.device)
# print(y.device)
# print(z.device)

tensor([3., 7.], dtype=torch.float64)
tensor([3., 2.], dtype=torch.float64)
tensor([3., 7.], dtype=torch.float64)
tensor([3., 7.], dtype=torch.float64)


In [ ]:
# with np.load('data/octa_sphere_5.npz') as npl:
#     v_s, f_s = npl['v'], npl['f']

# #Mesh
# v_m, f_m = igl.read_triangle_mesh("data/deer.obj")
# # v_m, f_m = igl.read_triangle_mesh("data/cat.obj")
# # v_m, f_m = igl.read_triangle_mesh("data/Beast.obj")

# #Cage
# v_c, f_c = igl.read_triangle_mesh("data/deer_cage.obj")
# # v_c, f_c = igl.read_triangle_mesh("data/cat_cage.obj")
# # v_c, f_c = igl.read_triangle_mesh("data/cc_part.obj")
# # v_c, f_c = igl.read_triangle_mesh("data/Beast_Cage.obj")

# # plt = mp.plot(v_m, f_m)



# n = igl.per_face_normals( v_c, f_c, np.array([1.0, 0, 0]) ) #normalized
# # n = torch.from_numpy(n)



# # cof = (v_c[f_c[:,1]]+v_c[f_c[:,1]]+v_c[f_c[:,1]])/3 # cage face의 center of mass


# # v_mci = np.array([0, 0, 0]) # shape vertex중 cage 안에 있는 vertex 들
# # v_mco = np.array([0, 0, 0]) # shape vertex중 cage 밖에 있는 vertex 들
# # v_mciidx = np.array([]) # cage 안에 있는 vertex 들의 index

# # for i in range(v_m.shape[0]):
# #     out = 0
# #     vtocof = cof-v_m[i]
# #     for j in range(f_c.shape[0]):
# #         if(vtocof[j]@n[j]<0):
# #             out = 1
# #             break
# #     if(out == 0):
# #         v_mci=np.vstack((v_mci, v_m[i]))
# #         v_mciidx = np.append(v_mciidx, np.array([i]))
# #     else:
# #          v_mco=np.vstack((v_mco, v_m[i]))
        
# # v_mci = v_mci[1:]
# # v_mco = v_mco[1:]

# # # plt.add_points(v_mci, shading={"point_color": "red", "point_size": 0.15})

# # f_mci = np.array([0, 0, 0]) # shape face중 cage 안에 있는 face 들
# # f_mco = np.array([0, 0, 0]) # shape face중 cage 밖에 있는 face 들
# # for i in range(f_m.shape[0]):
# #     if((f_m[i, 0] in v_mciidx) and (f_m[i, 1] in v_mciidx) and (f_m[i, 2] in v_mciidx)):
# #         f_mci=np.vstack((f_mci, f_m[i]))
# #     else:
# #         f_mco=np.vstack((f_mco, f_m[i]))

# # f_mci = f_mci[1:]
# # f_mco = f_mco[1:]

# # plt = mp.plot(v_m, f_mci)

# # lines_start = np.vstack( [v_c[f_c[:,0]], v_c[f_c[:,1]], v_c[f_c[:,2]]] )
# # lines_end =  np.vstack( [v_c[f_c[:,1]], v_c[f_c[:,2]], v_c[f_c[:,0]]] )


# # plt.add_lines( lines_start, lines_end, shading={"line_color": "red"});
# # plt.add_points(v_c, shading={"point_color": "green", "point_size": 0.1})

# # lines_start = np.vstack( [v_m[f_mci[:,0]], v_m[f_mci[:,1]], v_m[f_mci[:,2]]] )
# # lines_end =  np.vstack( [v_m[f_mci[:,1]], v_m[f_mci[:,2]], v_m[f_mci[:,0]]] )


# # plt.add_lines( lines_start, lines_end, shading={"line_color": "blue"})

# # lines_start = np.vstack( [v_m[f_mco[:,0]], v_m[f_mco[:,1]], v_m[f_mco[:,2]]] )
# # lines_end =  np.vstack( [v_m[f_mco[:,1]], v_m[f_mco[:,2]], v_m[f_mco[:,0]]] )


# # plt.add_lines( lines_start, lines_end, shading={"line_color": "green"})
# # # print(v_mci)

In [31]:
v_m, f_m = igl.read_triangle_mesh("../data/deer.obj")
v_c, f_c = igl.read_triangle_mesh("../data/deer_cage.obj") #obj 파일에는 vertex index를 1부터 표시하지만 이 함수로 표현되는 index는 0부터
n = igl.per_face_normals(v_c, f_c, np.array([1.0, 0, 0])) #normalized
# n = torch.from_numpy(n)

In [13]:
v_m, f_m = igl.read_triangle_mesh("../data/deer.obj")
v_c, f_c = igl.read_triangle_mesh("../data/deer_cage.obj")
n = igl.per_face_normals(v_c, f_c, np.array([1.0, 0, 0])) #normalized
n = torch.from_numpy(n)

def GCTriInt(p, v1, v2, eta):
    
    alpha = torch.acos((v2-v1)@(p-v1)/(torch.norm(v2-v1)*torch.norm(p-v1)))
    beta = torch.acos((v1-p)@(v2-p)/(torch.norm(v1-p)*torch.norm(v2-p)))
    
    #alpha(or beta) 가 거의 pi나 0에 가까울 경우 삼각형의 넓이가 거의 0 이라 적분값이 0 
    # if abs(alpha - np.pi) < EPS or abs(alpha) < EPS: return 0 
    # if abs(beta - np.pi) < EPS or abs(beta) < EPS: return 0
    
    l = (torch.norm(p-v1)**2)*(torch.sin(alpha)**2)
    c = torch.norm(p-eta)**2
    
   
    
    theta = pi - alpha
    S = torch.sin(theta)
    C = torch.cos(theta)
    
    d1 = torch.sqrt(l + c*(S**2))
    d2 = c*(1+C)+l+torch.sqrt(l**2+l*c*(S**2))
    
    I1 = -(1/2)*torch.sign(S)*(2*torch.sqrt(c)*torch.atan(torch.sqrt(c)*C/d1)
                               + torch.sqrt(l)*torch.log(2*torch.sqrt(l)*(S**2)*(1-2*c*C/d2)/((1-C)**2)))
    
    theta = pi - alpha - beta
    S = torch.sin(theta)
    C = torch.cos(theta)
    
    d1 = torch.sqrt(l + c*(S**2))
    d2 = c*(1+C)+l+torch.sqrt(l**2+l*c*(S**2))
    
    I2 = -(1/2)*torch.sign(S)*(2*torch.sqrt(c)*torch.atan(torch.sqrt(c)*C/d1)
                               + torch.sqrt(l)*torch.log(2*torch.sqrt(l)*(S**2)*(1-2*c*C/d2)/((1-C)**2)))

    
    return -(1/(4*pi))*abs(I1-I2-torch.sqrt(c)*beta) # Why abs?




def genCoords(V, T, v_m):
    # Input (tensor)
    # V : (cv, 3) (cv: # of cage vertex) - cage vertices (sorted by ID)
    # T : (cf, 3) (cf: # of cage face) - vertices IDs of faces
    # v_m : (n, 3) (n: # of shape vertex) - vertices of shape
    
    # Output
    # phi : (n, cv) : coordinate about cage's vertex 
    # psi : (n, cf) : coordinate about cage's face's normal
    
    phi = torch.zeros(len(v_m), len(V))
    psi = torch.zeros(len(v_m), len(T))
    for eta_idx, eta in enumerate(v_m):
        clear_output(wait=True)
        print(eta_idx+1,"/",len(v_m)," ", (eta_idx+1)/len(v_m)*100,"%")
        for f_idx, f in enumerate(T):
            v = torch.tensor([V[f[0]], V[f[1]], V[f[2]]], dtype = float)
            # print("v")
            # print(v)
            # print("eta")
            # print(eta)
            for l in range(3):
                v[l] -= eta 
            p = (v[0]@n[f_idx])*n[f_idx] 
            
            s = torch.zeros(3, dtype = float)
            I = torch.zeros(3, dtype = float)
            II = torch.zeros(3, dtype = float)
            N = torch.zeros((3, 3), dtype = float)
            
            for l in range(3):
                s[l] = torch.sign(torch.cross(v[l%3]-p, v[(l+1)%3]-p)@n[f_idx])          
                I[l] = GCTriInt(p, v[l%3], v[(l+1)%3], torch.zeros(3))              
                II[l] = GCTriInt(torch.zeros(3),  v[(l+1)%3], v[l%3], torch.zeros(3))
                q = torch.cross(v[(l+1)%3],  v[l%3])
                N[l] = q/torch.norm(q)
            
            I_f = - abs(s[0]*I[0]+s[1]*I[1]+s[2]*I[2])
            psi[eta_idx, f_idx] = -I_f
            w = I_f*n[f_idx] + II[0]*N[0]+II[1]*N[1]+II[2]*N[2]
            
            if(torch.norm(w) > 0.00001):
                for l in range(3):
                    phi[eta_idx, f[l]] += (N[(l+1)%3]@w)/(N[(l+1)%3]@v[l]) #하나의 face의 한 꼭짓점에 대한 phi component 계산값을 하나씩 축적해줌                 
    
    return psi, phi


v_m = torch.from_numpy(v_m)
psi, phi = genCoords(v_c, f_c, v_m) #psi : for face's normal, phi: for vertex

    

772 / 772   100.0 %


In [16]:
print(phi[0])

tensor([-1.3948e-04,  3.9419e-03, -3.2439e-03,  3.0819e-03, -4.7091e-03,
         3.2324e-03, -2.7490e-03,  4.3770e-03,  2.4454e-03,  3.4485e-03,
         4.8867e-03,  3.7662e-03,  4.3675e-03,  2.6422e-03,  7.3855e-03,
         3.5104e-03,  4.5651e-04,  2.0983e-04,  3.3748e-04,  4.9245e-04,
         2.0113e-03,  2.0695e-03,  7.6099e-03,  1.0890e-02,  1.6541e-02,
         1.9331e-02,  9.8426e-03,  5.4724e-03,  6.8886e-04, -2.8395e-03,
         1.0335e-02,  4.9573e-02,  1.4621e-02,  1.8055e-02,  2.3293e-01,
         1.9638e-01,  3.2137e-02,  1.9144e-02,  3.4601e-02,  2.2809e-02,
        -1.7504e-03,  3.0510e-03,  5.8065e-03,  5.8787e-03,  4.9934e-03,
         4.9922e-03,  3.5992e-03, -1.6306e-04,  5.4992e-03,  1.0733e-02,
         5.3108e-03,  3.8485e-03,  5.3459e-03,  5.5265e-03,  1.1346e-04,
         2.9044e-03,  4.2332e-03,  7.0508e-03,  2.7420e-03,  9.4934e-03,
         8.9001e-03,  5.7837e-02,  4.6296e-02,  2.2342e-02,  2.9470e-02,
         4.6278e-04,  3.7851e-03,  1.3020e-04,  3.6